name: "Pnpm Install"
description: "Try to install pnpm and duck out"
inputs:
  recursiveInstall: # id of input
    description: "Recursively install NPM packages"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
